forecastio:
    date:
        days: # weekdays in the future from now (1, 1 will look for tomorrow)
            from: 1
            to: 1
        hours:
            from: 11
            to: 19
    fields: # You can put any forecast.io API data point object here
        windSpeed:
            from: 3.4
            to: 11
        temperature:
            from: 10
            to: 50

    api:
        key: # see https://developer.forecast.io/

    latitude: 49.130833
    longitude: 10.935278

twitter: # Remove this block if you don't need Twitter
    api:
        key: # see https://apps.twitter.com/
        secret: # see https://apps.twitter.com/

    token:
        key: # see https://apps.twitter.com/
        secret: # see https://apps.twitter.com/

telegram: # Remove this block if you don't need Telegram
    api:
        token: # see https://core.telegram.org/bots
    target:
        chat_id: # see https://core.telegram.org/bots

trigger:
    hours: 3

message: "%d hours of good wind (>%d kts) tomorrow! http://de.windfinder.com/forecast/brombachsee_mitteldamm #brombachsee"
