forecastio:
    date:
        days: # weekdays in the future from now (1, 1 will look for tomorrow)
            from: 1
            to: 1
        hours:
            from: 11
            to: 19
    fields: # You can put any forecast.io API data point object here
        windSpeed:
            from: 3.4
            to: 11
        temperature:
            from: 10
            to: 50

    api:
        key: # see https://developer.forecast.io/

    latitude: 49.130833
    longitude: 10.935278

twitter:
    api:
        key: # see https://apps.twitter.com/
        secret: # see https://apps.twitter.com/

    token:
        key: # see https://apps.twitter.com/
        secret: # see https://apps.twitter.com/

pushbullet:
    api:
        key: # see https://www.pushbullet.com/account
    target: # USE ONLY ONE OF THESE, see https://docs.pushbullet.com/v2/pushes/
        channel_tag: # use to push to a channel
        device_iden: # use to push to a device
        email: # use to push to a user associated with an email
        client_iden: # use to push to all users who have granted OAuth access

trigger:
    hours: 3

message: "%d hours of good wind (>%d kts) tomorrow! http://de.windfinder.com/forecast/brombachsee_mitteldamm #brombachsee"
